version: '3.8'
services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        volumes:
            # - ./mysql-dump:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: profilems
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - "6603:3306"
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: pma
        # volumes:
        #     - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
        # restart: always
        # command: >
        #     sh -c "chmod +x /usr/local/bin/wait-for-it.sh && /usr/local/bin/wait-for-it.sh -t 0 db:3306 --strict -- echo 'db service is ready'"
        environment: 
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            # PMA_PASSWORD: root
        ports:
            - "8080:80"
    # web:
    #     depends_on: 
    #         - db
    #     image: tomcat:9.0.10
    #     # volumes:
    #     #     - ./target/ProfileManagement.war:/usr/local/tomcat/webapps/ProfileManagement.war
    #     restart: always
    #     ports:
    #         - '8082:8080'
    #     # environment: 
    #         # MYSQL_ROOT_PASSWORD: root
    #         # MYSQL_DATABASE: profilems
    #         # MYSQL_USER: root
    #         # MYSQL_PASSWORD: root
volumes:
    data-volume:
