version: '3.8'
services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        volumes:
            - ./mysql-dump:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: profilems
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - "6603:3306"
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: pma
        environment: 
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - "8080:80"
